logo: /assets/img/logo.png
description: Associate Professor
affiliation: Sun Yat-sen University, China
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
google_url: https://scholar.google.com/citations?user=Bo6PwnQAAAAJ
sysu_url: https://cse.sysu.edu.cn/teacher/Huangdan
title: Dan Huang (黄聃)
myemail: huangd79 at mail.sysu.edu.cn
